export const SELECTION_CLICKED = 'SELECTION_CLICKED';

export const START_RANGE_SELECTION = 'START_RANGE_SELECTION';
export const STOP_RANGE_SELECTION = 'STOP_RANGE_SELECTION';
export const CONTINUE_RANGE_SELECTION = 'CONTINUE_RANGE_SELECTION';
