export const DOT_CLICKED = 'DOT_CLICKED';

export const START_RANGE_SELECTION = 'START_RANGE_SELECTION';
export const STOP_RANGE_SELECTION = 'STOP_RANGE_SELECTION';
export const CONTINUE_RANGE_SELECTION = 'CONTINUE_RANGE_SELECTION';

export const SET_CURRENT_BRUSH = 'SET_CURRENT_BRUSH';

export const SET_HOVERED_ELEMENT = 'SET_HOVERED_ELEMENT';
export const REMOVE_HOVERED_ELEMENT = 'REMOVE_HOVERED_ELEMENT';
